---
title: Workshop series schedule
---

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">

<h2 id="week-1" class="panel-title">
<a data-toggle="collapse" href="#collapse1">Week 1: 09/07. Introduction to R</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse" style="margin:12px">
<p><b>Topics:</b> Introduction to R and R Studio. Packages. Working Directory. Dataframes and functions.</p>
<p><b>Registration:</b> <a href="https://projectmosaic.uncc.edu/events/r-essentials-part-1/">Sign-up Link.</a></p>

<h4>Reference material</h4>
<ul>
<li><p>Anderson, B. (2017). <a href="https://github.com/geanders/RProgrammingForResearch/raw/master/slides/CourseNotes_Week1.pdf">Week 1 Slides: Preliminaries in R.</a> <i>R Programming for Research Course</i>.</p>
</li>
<li><p>R Studio (2017). <a href="https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf">R Studio IDE Cheatsheet.</a> </p>
</li>
</ul>

<h4>Code</h4>
<ul>
<li><p>Anderson, B. (2017). <a href="https://geanders.github.io/RProgrammingForResearch/r-preliminaries.html">Week 1: Preliminaries in R.</a> <i>R Programming for Research Course</i>.</p>
</li>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/workflow-basics.html"> Workflow Basics</a>. <i>R for Data Science</i>. </p>
</li>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/workflow-scripts.html"> Workflow Scripts</a>. <i>R for Data Science</i>. </p>
</li>
<li><p><a href="https://gist.github.com/wesslen/ae9aca04b491a064764b13239fb17489"> Intro Twitter R Script</a>. <a href="https://github.com/wesslen/RVisTutorial/raw/master/RTutorialTwitter.zip"> Zip File </a> </p>
</li>
<li><p><a href="http://vnijs.github.io/radiant/"> R Radiant Package for Statistics & Machine Learning</a>. </p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-2" class="panel-title">
<a data-toggle="collapse" href="#collapse2">Week 2: 09/14. Data Management</a>
</h2>
</div>
<div id="collapse2" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> Importing data (csv, Stata, SAS). Data wrangling, aggregation and filtering (dplyr).</p>
<p><b>Registration:</b> <a href="https://projectmosaic.uncc.edu/events/r-essentials-part-2/">Sign-up Link.</a></p>

<h4>Reference material</h4>
<ul>
<li><p>Anderson, B. (2017). <a href="https://github.com/geanders/RProgrammingForResearch/raw/master/slides/CourseNotes_Week2.pdf">Week 2 Slides: Entering & Cleaning Data.</a> <i>R Programming for Research Course</i>.</p>
</li>
<li><p>R Studio (2017). <a href="https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-import-cheatsheet.pdf">R Studio Data Import Cheatsheet.</a> </p>
</li>
<li><p><a href="https://wesslen.github.io/fall2017-rworkshops/code/week-2/week2workshop.zip">Zip File (Data, Code).</a></p>
</li>
</ul>

<h4>Code</h4>
<ul>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/data-import.html"> Data Import</a>. <i>R for Data Science</i>. </p>
</li>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/transform.html"> Data Transformation</a>. <i>R for Data Science</i>. </p>
</li>
</ul>

<h4>Optional Readings</h4>
<ul>
<li><p>R Studio (2017). <a href="https://www.rstudio.com/resources/webinars/importing-data-into-r/">R Studio Importing Data into R Webinar.</a> </p>
</li>
<li><p>Wickham, H. (2017). <a href="http://adv-r.had.co.nz/Data-structures.html">Data Structures.</a> <i>Advanced R</i>. </p>
</li>
<li><p><a href="http://webpages.uncc.edu/rwesslen/blogs/01-beerandtweeting.html">Beer in Charlotte (Twitter Tutorial) Blog Post</a> </p>
</li>
</ul>

</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-3" class="panel-title">
<a data-toggle="collapse" href="#collapse3">Week 3: 09/21. Tidyverse</a>
</h2>
</div>
<div id="collapse3" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> Overview of Tidyverse: tidyr, dplyr, ggplot2, readr, purrr</p>
<p><b>Registration:</b> <a href="https://projectmosaic.uncc.edu/events/r-essentials-part-3/">Sign-up Link.</a></p>

<h4>Reference material</h4>
<ul>
<li><p>R Studio (2017). <a href="https://www.tidyverse.org/">Tidyverse.</a> </p>
</li>
<li><p>Soltoff, B. (2017). <a href="http://cfss.uchicago.edu/extras/cm003_slides.html">Data transformation and exploratory data analysis slides</a>. <i>Computing for the Social Sciences</i></p>
</li>
<li><p>R Studio (2017). <a href="https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-transformation-cheatsheet.pdf">R Studio Data Transformation Cheatsheet</a>. </p>
</li>
</ul>

<h4>Code</h4>
<ul>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/tidy-data.html"> Tidy Data</a>. <i>R for Data Science</i>. </p>
</li>
<li><p>Soltoff, B. (2017). <a href="http://cfss.uchicago.edu/datawrangle_dplyr.html">`dplyr` in brief</a>. <i>Computing for the Social Sciences</i>. </p>
</li>
</ul>

<h4>Optional Readings</h4>
<ul>
<li><p>Bryan, J. (2017). <a href="https://jennybc.github.io/purrr-tutorial/">purrr tutorial</a>. </p>
</li>
<li><p>Gillespie G., & Lovelace, R. (2017). <a href="https://csgillespie.github.io/efficientR/data-carpentry.html">Efficient data carpentry.</a>. <i>Efficient R programming</i>. </p>
</li>
</ul>

</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-4" class="panel-title">
<a data-toggle="collapse" href="#collapse4">Week 4: 09/28. Reproducible Research</a>
</h2>
</div>
<div id="collapse4" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> R Markdown and Bookdown. Introduction to Git</p>
<p><b>Registration:</b> <a href="https://projectmosaic.uncc.edu/events/reproducible-research-with-rmarkdown-and-git/">Sign-up Link.</a></p>

<h4>Reference material</h4>
<ul>
<li><p>Anderson, B. (2017). <a href="https://github.com/geanders/RProgrammingForResearch/raw/master/slides/CourseNotes_Week5.pdf">Week 5 Slides: Reproducible Research.</a> <i>R Programming for Research Course</i>.</p>
</li>
<li><p><a href="https://wesslen.github.io/fall2017-rworkshops/code/week-4/week4workshop.zip">Zip File (Data, Code).</a></p>
</li>
<li><p>Bryan, J. (2017).<a href="https://speakerdeck.com/jennybc/ubc-stat545-2015-cm001-intro-to-course"> STAT545 Course 1 Slides</a>. </p>
</li>
<li><p>Bryan, J. (2017).<a href="http://happygitwithr.com/big-picture.html"> Happy with Git and GitHub for the useR</a>. </p>
</li>
</ul>

<h4>Optional Readings</h4>
<ul>
<li><p>Grolemund G., & Wickham, H. (2017).<a href="http://r4ds.had.co.nz/r-markdown.html"> RMarkdown</a>. <i>R for Data Science</i>. </p>
</li>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/r-markdown-formats.html"> RMarkdown Formats</a>. <i>R for Data Science</i>. </p>
</li>
<li><p>R Studio (2016). <a href="https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf">RMarkdown Cheatsheet</a>. </p>
</li>
<li><p><a href="http://rmarkdown.rstudio.com/lesson-1.html">RStudio RMarkdown Lessons</a>. </p>
</li>
<li><p>Wickham, H. (2015). <a href="http://r-pkgs.had.co.nz/git.html">Git and Github</a>. <i>R Packages</i>. </p>
</li>
</ul>


</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-5" class="panel-title">
<a data-toggle="collapse" href="#collapse5">Week 5: 10/12. Visualizations</a>
</h2>
</div>
<div id="collapse5" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> Introduction to visualizations. ggplot2. Interactive visualizations using HTMLWidgets.</p>

<h4>Reference material</h4>
<ul>
<li><p><a href="https://wesslen.github.io/fall2017-rworkshops/code/week-5/week5workshop.zip">Zip File (Data, Code).</a></p>
</li>
<li><p>R Studio. (2017) <a href="http://www.htmlwidgets.org/">R Studio HTML Widgets</a>.</p>
</li>
<li><p>R Studio. (2017) <a href="http://shiny.rstudio.com/">R Studio Shiny</a>.</p>
</li>
<li><p>R Studio. (2017) <a href="https://www.rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf">R Studio Data Visualization Cheatsheet</a>.</p>
</li>
</ul>


<h4>Code</h4>
<ul>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/data-visualisation.html">Data Visualization (ggplot2).</a> <i>R for Data Science</i>. </p>
</li>
<li><p>Grolemund G., & Wickham, H. (2017). <a href="http://r4ds.had.co.nz/exploratory-data-analysis.html">Exploratory Data Analysis.</a> <i>R for Data Science</i>. </p>
</li>
<li><p>HTML Widgets: <a href="https://plot.ly/r/">plotly</a>, <a href="https://rstudio.github.io/leaflet/">leaflet</a>, <a href="https://hrbrmstr.github.io/streamgraph/">streamgraph</a>, <a href="http://datastorm-open.github.io/visNetwork/">visNetwork</a>.</p>
</li>
</ul>

</div>
</div>
</div>

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-6" class="panel-title">
<a data-toggle="collapse" href="#collapse6">Week 6: 10/19. Acquiring Data (APIs)</a>
</h2>
</div>
<div id="collapse6" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> Define API's. Twitter's Public API (REST and Stream). Facebook API.</p>

<h4>Reference material</h4>
<ul>
<li><p>Kearney, M. (2017). <a href="https://mkearney.github.io/rtweet/index.html"> rtweet </a>. GitHub repository.</p>
</li>
<li><p>Barberá, P. (2017). <a href="https://github.com/pablobarbera/Rfacebook"> Rfacebook </a>. GitHub repository.</p>
</li>
<li><p><a href="https://github.com/wesslen/fall2017-rworkshops/raw/master/code/week-6/week6workshop.zip">Zip File (Data, Code).</a> <a href="https://rpubs.com/ryanwesslen/socialmedia"> Slides.</a></p>
</ul>

<h4>Optional Readings</h4>
<ul>
<li><p>Barberá, P. (2017). <a href="https://github.com/pablobarbera/POIR613/raw/master/slides/03-scraping.pdf"> Scraping the Web </a>. <i> POIR 613: Measurement Models and Statistical Computing</i>. </p>
</li>
<li><p>Tufekci, Z. (2014). <a href="https://arxiv.org/pdf/1403.7400.pdf"> Big questions for social media big data: Representativeness, validity and other methodological pitfalls.</a> arXiv preprint arXiv:1403.7400.<p>
</li>
<li><p>Morstatter, F., & Liu, H. (2017). <a href="http://www.public.asu.edu/~fmorstat/paperpdfs/osnem_preprint.pdf"> Discovering, assessing, and mitigating data bias in social media.</a> Online Social Networks and Media, 1, 1-13.<p>
</li>
</ul>
</div>
</div>
</div>

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-7" class="panel-title">
<a data-toggle="collapse" href="#collapse7">Week 7: 10/26. Social Networks</a>
</h2>
</div>
<div id="collapse7" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> Basic concepts in social network analysis. Centrality measures. Network visualization.</p>

<h4>Reference material</h4>
<ul>
<li><p>Barberá, P. (2017). <a href="https://github.com/pablobarbera/POIR613/raw/master/slides/11-networks-intro.pdf"> Intro to Social Network </a>. <i> POIR 613: Measurement Models and Statistical Computing</i>. </p>
</li>
<li><p>Denny, M. (2014). <a href="http://www.mjdenny.com/workshops/SN_Theory_I.pdf"> Social Network Analysis </a>. <i> Institute for Social Science Research </i>. </p>
</li>
<li><p>Ognyanova, K. (2017). <a href="http://kateto.net/network-visualization">Network visualization with R</a>. <i> POLNET 2017 Workshop</i>, Columbus, OH.<p>
</li>
<li><p><a href="https://github.com/wesslen/fall2017-rworkshops/raw/master/code/week-7/week7workshop.zip">Zip File (Data, Code).</a> </p>
</ul>
</ul>

<h4>Optional</h4>
<ul>
<li><p>Lazer, D., Pentland, A. S., Adamic, L., Aral, S., Barabasi, A. L., Brewer, D., ... & Jebara, T. (2009). <a href="http://fowler.ucsd.edu/computational_social_science.pdf">Life in the network: the coming age of computational social science</a>. <i>Science</i>, 323(5915), 721-3.</p>
</li>
<li><p>McPherson, M., Smith-Lovin, L., & Cook, J. M. (2001). <a href="http://www.annualreviews.org/doi/abs/10.1146/annurev.soc.27.1.415">Birds of a feather: Homophily in social networks.</a> <i>Annual review of sociology</i>, 27(1), 415-444.</p>
</li>
</ul>

<h4>Code</h4>
<ul>
<li><p>Barberá, P. (2017). <a href="http://pablobarbera.com/POIR613/code/15-networks-intro-visualization.html">Introduction to social network analysis with R</a>. <i> POIR 613: Measurement Models and Statistical Computing</i>.</p>
</li>
<li><p>Barberá, P. (2017). <a href="http://pablobarbera.com/POIR613/code/16-networks-descriptive-analysis.html">Social network analysis with R: Descriptive analysis</a>. <i> POIR 613: Measurement Models and Statistical Computing</i>.</p>
</li>
<li><p><a href="https://cdn.rawgit.com/wesslen/fall2017-rworkshops/f51a2295/code/week-7/week7workshop/02-interactive-networks/03-visnetwork.html">Interactive Networks (visNetwork)</a>. </p>
</li>
<li><p><a href="https://rawgit.com/wesslen/summer2017-socialmedia/master/day2/twitter-social-networks.html">Retweet & Reply Interactive Networks with visNetwork</a>.</p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-8" class="panel-title">
<a data-toggle="collapse" href="#collapse8">Week 8: 11/02. Machine Learning</a>
</h2>
</div>
<div id="collapse8" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> Predictive versus explanatory analysis. Evaluation: Holdout/Cross Validation. Supervised and unsupervised machine learning. Regularization. </p>

<h4>Reference material</h4>
<ul>
<li><p>Mullainathan, S., & Spiess, J. (2017). <a href="https://www.aeaweb.org/articles?id=10.1257/jep.31.2.87">Machine Learning: An Applied Econometric Approach</a>. <i>Journal of Economic Perspectives</i>, 31(2), 87-106.</p>
</li>
<li><p>Grimmer, J. (2015). <a href="https://www.cambridge.org/core/services/aop-cambridge-core/content/view/S1049096514001784">We are all social scientists now: how big data, machine learning, and causal inference work together</a>. <i>PS: Political Science & Politics</i>, 48(1), 80-83.</p>
</li>
<li><p>Athey, S., & Imbens, G. (2015). <a href="http://www.nasonline.org/programs/sackler-colloquia/documents/athey.pdf">Machine Learning Methods for Causal Effects</a>. </p>
</li>
<li><p>Barberá, P. (2017). <a href="http://pablobarbera.com/POIR613/slides/08-supervised-learning.pdf"> Supervised Machine Learning </a>. <i> POIR 613: Measurement Models and Statistical Computing</i>. </p>
</li>
</ul>


<h4>Code</h4>
<ul>
<li><p><a href="https://topepo.github.io/caret/index.html">Supervised Machine Learning: `caret` tutorial</a></p>
</li>
<li><p>Amunategui, M. (2014). <a href="https://amunategui.github.io/binary-outcome-modeling/">Modeling 101 - Predicting Binary Outcomes with R, gbm, glmnet, and {caret}</a></p>
</li>
<li><p><a href="https://github.com/wesslen/fall2017-rworkshops/raw/master/code/week-8/week8workshop.zip">Zip File (Data, Code).</a> </p>
</ul>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-9" class="panel-title">
<a data-toggle="collapse" href="#collapse9">Week 9: 11/16. Intro to Text</a>
</h2>
</div>
<div id="collapse9" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> tidytext. Bag of words. Word frequencies, TF-IDF and Zipf's Law. Dictionary-based methods.</p>

<h4>Reference material</h4>
<ul>
<li><p>Rothenberg, M. (2017) <a href="http://emojitracker.com/">Emoji Tracker</a>.</p>
</li>
<li><p>University of Vermont Complex Systems Center (2017) <a href="http://hedonometer.org">Hedonometer</a>.</p>
</li>
<li><p>Silge, J. & Robinson, D. (2017) <a href="https://cran.r-project.org/web/packages/tidytext/vignettes/tidytext.html">Introduction to `tidytext`</a>.</p>
</li>
</ul>

<h4>Optional Readings</h4>
<ul>
<li><p>Young, L., & Soroka, S. (2012). <a href="http://www.tandfonline.com/doi/abs/10.1080/10584609.2012.671234">Affective news: The automated coding of sentiment in political texts</a>. <i>Political Communication</i>, 29(2), 205-231.</p>
</li>
<li><p>Tausczik, Y. R., & Pennebaker, J. W. (2010). <a href="http://journals.sagepub.com/doi/abs/10.1177/0261927X09351676">The psychological meaning of words: LIWC and computerized text analysis methods</a>. <i>Journal of language and social psychology</i>, 29(1), 24-54.</p></li>
</ul>

</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-10" class="panel-title">
<a data-toggle="collapse" href="#collapse10">Week 10: 11/30. Text as Data</a>
</h2>
</div>
<div id="collapse10" class="panel-collapse collapse" style="margin:12px">

<p><b>Topics:</b> Text as Data. Supervised (Text Classification) and Unsupervised Models (Topic Models, Word Scaling and Word Embedding)</p>

<h4>Reference material</h4>
<ul>
<li><p>Benoit, K. et al. (2017) <a href="http://quanteda.io/articles/quickstart.html">Getting Started with `quanteda`</a>.</p>
</li>
<li><p>Blei, D. M. (2012). <a href="http://dl.acm.org/citation.cfm?id=2133826">Probabilistic topic models.</a> <i>Communications of the ACM</i>, 55(4), 77-84.</p>
</li>
<li><p>Grimmer, J., & Stewart, B. M. (2013). <a href="https://www.cambridge.org/core/journals/political-analysis/article/div-classtitletext-as-data-the-promise-and-pitfalls-of-automatic-content-analysis-methods-for-political-textsdiv/F7AAC8B2909441603FEB25C156448F20">Text as data: The promise and pitfalls of automatic content analysis methods for political texts</a>. <i>Political analysis</i>, 21(3), 267-297.<p>
</li>
</ul>

<h4>Optional Readings</h4>
<ul>
<li><p>Roberts, M. E., Stewart, B. M., Tingley, D., Lucas, C., Leder‐Luis, J., Gadarian, S. K., ... & Rand, D. G. (2014). <a href="http://authors.library.caltech.edu/52278/7/topicmodelsopenendedexperiments.pdf">Structural Topic Models for Open‐Ended Survey Responses.</a> <i>American Journal of Political Science</i>, 58(4), 1064-1082.</p>
</li>
<li><p>Lowe, W. (2008). <a href="http://www.jstor.org/stable/25791945">Understanding wordscores</a>. <i>Political Analysis</i>, 16(4), 356-371.</p>
</li>
<li><p>Gentzkow, M., Kelly, B. T., & Taddy, M. (2017). <a href="https://ssrn.com/abstract=2934001">Text as Data</a>, Working paper.</p>
</li>
<li><p>Denny, M. J., & Spirling, A. (2017). <a href="http://www.nyu.edu/projects/spirling/documents/preprocessing.pdf">Text preprocessing for unsupervised learning: why it matters, when it misleads, and what to do about it.</a> Working paper, New York University.</p>
</li>
<li><p>Mikolov, T., Chen, K., Corrado, G., & Dean, J. (2013). <a href="https://arxiv.org/pdf/1301.3781.pdf">Efficient estimation of word representations in vector space.</a> arXiv preprint arXiv:1301.3781.</p>
</li>
</ul>

<h4>Code</h4>
<ul>
<li><p><a href="">Text Classification</a></p>
</li>
<li><p><a href="">Topic models</a></p>
</li>
</ul>
</div>
</div>
</div>
</div>

